

import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.List;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author NOTEBOOK
 */
public class MainFrame extends javax.swing.JFrame {
    public List<String> kisaltmalar=new ArrayList<String>();
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("Cumleleri Ayir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jButton2.setText("Temizle");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(jButton1)
                .addGap(280, 280, 280))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        kisaltmaoku();
        String cumleler = jTextArea1.getText();
        String[] satirlar = cumleler.split("\n");
        String geciciCumle="";
        cumleler=cumleler.replaceAll("\\s+"," ");
        for (int i = 0; i < satirlar.length; i++) {
            satirlar[i]=satirlar[i].trim();
            String[] kelimeler = satirlar[i].split(" ");
            if(kelimeler[0].equals("")){
                jTextArea2.append("\n"+geciciCumle);
                geciciCumle="";
            }
            for (int j = 0; j < kelimeler.length; j++) {
                String kelime=kelimeler[j];
                for (int k = 0; k < kelime.length(); k++) { //kelime kontrolleri
                    if(kelime.charAt(k)=='!' || kelime.charAt(k)=='?' || kelime.charAt(k)==':'){
                        geciciCumle=geciciCumle+kelime.charAt(k);
                          jTextArea2.append("\n"+geciciCumle);
                          geciciCumle="\n";
                    }
                    else if(kelime.charAt(k)=='.'){// . kontrolu
                        geciciCumle=geciciCumle+kelime.charAt(k);
                          if(kisaltmaAra(kelime) || kelime.matches("([0-9]*.[0-9]+[e]?)*") || kelime.matches("([0-9]+.[0-9]*[e]?)*") ){
                          }
                          else if(kelime.matches("[a-zA-ZğĞçÇşŞüÜöÖıİ()\\{\\}\\[\\]]*\\.[.]+[a-zA-ZğĞçÇşŞüÜöÖıİ()\\{\\}\\[\\]]*")){   //birden fazla nokta yanyana ise
                                  for (int l = k+1; l < kelime.length(); l++) {
                                      
                                      if(kelime.charAt(l)=='.'){
                                        geciciCumle=geciciCumle+kelime.charAt(l);
                                      }
                                      if(kelime.length()-1==l){
                                          jTextArea2.append("\n"+geciciCumle);
                                          if(l+1<=kelime.length())
                                          geciciCumle="\n"+kelime.substring(l+1,kelime.length());
                                          else
                                          geciciCumle="\n";
                                          k=l;
                                          //break;
                                      }
                                  }
                                  
                              }
                          else{
                              jTextArea2.append("\n"+geciciCumle);
                              
                              if(k+1<kelime.length())
                              geciciCumle=kelime.substring(k+1,kelime.length());
                              geciciCumle="\n";
                          }
                    }
                    else{
                        geciciCumle=geciciCumle+kelime.charAt(k);
                    }
                }
                if(!geciciCumle.equals(""))
                geciciCumle=geciciCumle+" ";
            }
        }
        if(!geciciCumle.equals("\n")){
        jTextArea2.append("\n"+geciciCumle);
        geciciCumle="\n";
        }
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTextArea2.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    public void kisaltmaoku() {
        
        try {
            File file = new File("k.txt");
            BufferedReader br = new BufferedReader(new FileReader(file));
            String line;
            while((line=br.readLine())!= null){
                kisaltmalar.add(line);
            }
            br.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            
        }
        
    }
    public boolean kisaltmaAra(String kelime){
        for (int i = 0; i < kisaltmalar.size(); i++) {
            if(kelime.equalsIgnoreCase(kisaltmalar.get(i))){
            return true;
            }
        }
        return false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
